/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/电子签名': RouteRecordInfo<'/posts/电子签名', '/posts/电子签名', Record<never, never>, Record<never, never>>,
    '/posts/钉钉官网动效简易实现': RouteRecordInfo<'/posts/钉钉官网动效简易实现', '/posts/钉钉官网动效简易实现', Record<never, never>, Record<never, never>>,
    '/posts/轨迹动画': RouteRecordInfo<'/posts/轨迹动画', '/posts/轨迹动画', Record<never, never>, Record<never, never>>,
    '/posts/路由history部署后刷新404': RouteRecordInfo<'/posts/路由history部署后刷新404', '/posts/路由history部署后刷新404', Record<never, never>, Record<never, never>>,
    '/posts/微前端原理': RouteRecordInfo<'/posts/微前端原理', '/posts/微前端原理', Record<never, never>, Record<never, never>>,
    '/posts/bilibili': RouteRecordInfo<'/posts/bilibili', '/posts/bilibili', Record<never, never>, Record<never, never>>,
    '/posts/createVNode_render创建notify组件': RouteRecordInfo<'/posts/createVNode_render创建notify组件', '/posts/createVNode_render创建notify组件', Record<never, never>, Record<never, never>>,
    '/posts/js实现瀑布流': RouteRecordInfo<'/posts/js实现瀑布流', '/posts/js实现瀑布流', Record<never, never>, Record<never, never>>,
    '/posts/monorepo子进程打包packages': RouteRecordInfo<'/posts/monorepo子进程打包packages', '/posts/monorepo子进程打包packages', Record<never, never>, Record<never, never>>,
    '/posts/pnpm': RouteRecordInfo<'/posts/pnpm', '/posts/pnpm', Record<never, never>, Record<never, never>>,
    '/posts/tinyMCE': RouteRecordInfo<'/posts/tinyMCE', '/posts/tinyMCE', Record<never, never>, Record<never, never>>,
    '/posts/ViewTransition': RouteRecordInfo<'/posts/ViewTransition', '/posts/ViewTransition', Record<never, never>, Record<never, never>>,
    '/posts/vue组件库环境搭建': RouteRecordInfo<'/posts/vue组件库环境搭建', '/posts/vue组件库环境搭建', Record<never, never>, Record<never, never>>,
    '/posts/WebAnimationDirective': RouteRecordInfo<'/posts/WebAnimationDirective', '/posts/WebAnimationDirective', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
