name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
# 任务id
  buildBlog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    name: Node ${{ matrix.node }} sample
    # strategy:
    #   matrix:
    #     node-version: [16.x]
    #     os: [ubuntu-latest]
    #   fail-fast: false

    steps:
        - uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node }}
          # node-version: ${{ matrix.node-version }}
          # registry-url: https://registry.npmjs.org/

      - name: 📦 Install Dependencies
        run: npm i

      - name: 🌌 Build Valaxy Blog
        run: npm run build

      - name: 🪤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
